version: "3.9"
services:
  db:
    image: postgres:14.0
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "maindb"
      POSTGRES_USER: "psquser"
      POSTGRES_PASSWORD: "superpsqpasswd"
    ports:
      - "5432:5432"
  redis:
    container_name: 'redis'
    image: 'redis:3.2.0'
    ports:
      - '6379:6379'
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEFAULT_AUTO_FIELD=BigAutoField
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "python3 ./manage.py wait_for_db &&
             python3 ./manage.py makemigrations &&
             python3 ./manage.py migrate &&
             python3 ./manage.py collectstatic &&
             python3 ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  nginx:
    image: nginx:latest
    container_name: ngnix
    ports:
      - "8100:8000"
    volumes:
      - ./:/
      - ./nginx.conf:/etc/nginx.conf/conf.d
    depends_on:
      - web
    networks:
      - default