version: "3.9"
services:
  db:
    image: postgres:14.0
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "maindb"
      POSTGRES_USER: "psquser"
      POSTGRES_PASSWORD: "superpsqpasswd"
    ports:
      - "5432:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db